# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgpins.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# pkgpins: Facilitates Results Caching in R Packages Using the Pins Package
# Copyright (C) 2023 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c(".",
                                 "created",
                                 "file_size",
                                 "meta",
                                 "name",
                                 "pins_api_version",
                                 "pin_hash"))

ls_board_paths <- function(pkg) {
  
  tools::R_user_dir(package = "pkgpins",
                    which = "cache") %>%
    fs::dir_ls(type = "dir",
               regexp = glue::glue("/{pkg}(-.+)?$"))
}

#' Cache the result of an expression
#'
#' One-stop solution to add caching to any R expression, for example from within a function. See the examples.
#'
#' `expr` is evaluated in the environment that `with_cache()` is called from.
#'
#' See [hash_fn_call()] for details about how the pin name is constructed that uniquely identifies `expr` in the `pkg`'s user-cache pins board.
#'
#' @inheritParams board
#' @param expr Expression to cache.
#' @param pkg_versioned Whether or not to make the caching dependent on the version number of `pkg`. If `FALSE`, caching is agnostic about `pkg`'s version
#'   number. Otherwise, a separate user-cache pins board is created each time `pkg`'s version number changes (e.g. after an upgrade), ensuring to never return
#'   cached results from a different (old) package version, irrespective of `cache_lifespan`.
#' @param from_fn Name of the function that `expr` is cached from, i.e. the name of the function that `with_cache()` is called from. A character scalar.
#' @param ... Arguments received by `from_fn` on which the caching should depend. This is fundamental to determine whether `expr` was already cached or not. The
#'   arguments must be specified _unnamed_ (see examples). `r pkgsnip::param_label("dyn_dots_support")`
#' @param use_cache `r pkgsnip::param_label("use_cache")`
#' @param cache_lifespan `r pkgsnip::param_label("cache_lifespan")` 
#'
#' @return The result of evaluating `expr`, from cache if `use_cache = TRUE` and a cached result exists that hasn't exceeded `cache_lifespan`.
#' @family high_lvl
#' @export
#'
#' @examples
#' # if the fn below would be part of a real package, we could instead define `this_pkg` globally
#' # using `this_pkg <- utils::packageName()`; instead, we now cache to pkgpins's cache (which
#' # itself never uses the cache)
#' this_pkg <- "pkgpins"
#' 
#' # let's define a fn that returns R pkg sys deps from cache
#' pkg_sys_deps <- function(pkg,
#'                          use_cache = TRUE,
#'                          cache_lifespan = "6h") {
#'   pkgpins::with_cache(
#'     expr = purrr::list_flatten(jsonlite::fromJSON(txt = paste0("https://sysreqs.r-hub.io/pkg/",
#'                                                                pkg),
#'                                                   simplifyVector = FALSE)),
#'     pkg = this_pkg,
#'     from_fn = "pkg_sys_deps",
#'     pkg,
#'     use_cache = use_cache,
#'     cache_lifespan = cache_lifespan
#'   )
#' }
#' 
#' # now get the sys deps for git2r for the first time (populating the cache)
#' pkg_sys_deps("git2r")
#' 
#' \dontrun{
#' # for the `cache_lifespan` (we've set a default of 6h), the cached result will be returned
#' # (as long as `use_cache = TRUE`):
#' bench::mark("with cache" = pkg_sys_deps("git2r"),
#'             "without cache" = pkg_sys_deps("git2r", use_cache = FALSE),
#'             iterations = 10,
#'             relative = TRUE)}
#' 
#' # purge cache from the above example
#' pkgpins::board(pkg = "pkgpins") |> pkgpins::purge_cache()
with_cache <- function(expr,
                       pkg,
                       from_fn,
                       ...,
                       pkg_versioned = TRUE,
                       use_cache = TRUE,
                       cache_lifespan = "1 day") {
  
  checkmate::assert_flag(use_cache)
  
  fetch <- TRUE
  
  if (use_cache) {
    
    board <- board(pkg = pkg,
                   pkg_versioned = pkg_versioned)
    id <- hash_fn_call(from_fn = from_fn,
                       ...)
    
    # NOTE: we can't use `get_obj()` here because in case of return value `NULL` we wouldn't know whether it means there's no cached result or the cached
    #       result is just `NULL`
    if (is_cached(board = board,
                  id = id,
                  max_age = cache_lifespan)) {
      
      result <- pins::pin_read(board = board,
                               name = id)
      fetch <- FALSE
    }
  }
  
  if (fetch) {
    result <- rlang::eval_bare(expr = expr,
                               env = parent.frame(n = 2L))
  }
  
  if (use_cache && fetch) {
    cache_obj(board = board,
              x = result,
              id = id)
  }
  
  result
}



#' Get a package's user-cache pins board
#'
#' Returns a `pkg`'s user-cache pins board. The board is automatically created if it doesn't already exist.
#'
#' @param pkg Package name. A character scalar.
#' @param pkg_versioned Whether or not to make the board name dependent on `pkg`'s version number. If `FALSE`, the board is agnostic about `pkg`'s version
#'   number. Otherwise, a separate board is created for each `pkg` version number (e.g. after an upgrade).
#'
#' @return The user-cache pins board belonging to `pkg` (and its version number if `pkg_versioned = TRUE`). An object of class
#'   [`pins_board_folder`][pins::board_folder].
#' @family pkg_cache_mgmt
#' @export
board <- function(pkg,
                  pkg_versioned = TRUE) {
  
  checkmate::assert_string(pkg)
  checkmate::assert_flag(pkg_versioned)
  
  if (pkg_versioned) {
    
    pkg %<>% paste(utils::packageVersion(pkg = pkg),
                   sep = "-")
  }
  
  tools::R_user_dir(package = "pkgpins",
                    which = "cache") %>%
    fs::path(pkg) %>%
    pins::board_folder(versioned = FALSE)
}

#' Get a package's user-cache pins board path
#'
#' Returns the filesystem path to the `pkg`'s user-cache pins board. Note that this path depends on the operating system this function is called from.
#' 
#' It shouldn't be necessary to rely on this function for the tasks this package is intended to perform, though.
#'
#' @param board [Package's user-cache pins board][board()].
#'
#' @return `r pkgsnip::return_label("path")`
#' @family pkg_cache_mgmt
#' @export
path_cache <- function(board) {
  
  checkmate::assert_class(board,
                          classes = "pins_board_folder")
  board$path
}

#' List all objects in a package's user-cache pins board
#'
#' Lists all objects stored in a `pkg`'s user-cache pins board.
#'
#' @inheritParams path_cache
#'
#' @return A [tibble][tibble::tbl_df] containing the columns `id`, `date_time_cached`, `file_size` and `pins_api_version`.
#' @family pkg_cache_mgmt
#' @export
ls_cache <- function(board) {
  
  checkmate::assert_class(board,
                          classes = "pins_board_folder")
  
  pins::pin_search(board = board) %>%
    dplyr::mutate(pins_api_version = meta %>% purrr::map_dbl(purrr::chuck, "api_version")) %>%
    dplyr::select(id = name,
                  date_time_cached = created,
                  file_size,
                  pins_api_version)
}

#' Clear a package's user-cache pins board
#'
#' Deletes all objects from a package's user-cache pins board that exceed a certain `max_age`. If `board` is `pkg_versioned`, additionally deletes all
#' user-cache pins boards belonging to versions of the package other than the currently installed one.
#'
#' This function could be called on package load/unload, for example.
#'
#' @inheritParams path_cache
#' @param max_age Age above which cached objects will be deleted. A valid [lubridate duration][lubridate::as.duration]. Defaults to 1 day (24 hours).
#'
#' @return `board`, invisibly.
#' @family pkg_cache_mgmt
#' @export
#'
#' @examples
#' \dontrun{
#' # delete all cached results that are older than 7 days at once on package load:
#' .onLoad <- function(libname, pkgname) {
#'   pkgpins::clear_cache(board = pkgpins::board(pkg = pkgname),
#'                        max_age = "7 days")
#' }}
clear_cache <- function(board,
                        max_age = "1 day") {
  
  # delete boards from different pkg versions
  path_cache <- fs::path_real(path_cache(board))
  board_name <- fs::path_file(path_cache)
  incl_pkg_version <- stringr::str_detect(board_name, "-")
  
  if (incl_pkg_version) {
    
    board_name %>%
      stringr::str_extract("^[^-]+") %>%
      ls_board_paths() %>%
      setdiff(y = path_cache) %>%
      purrr::walk(fs::dir_delete)
  }
  
  # delete results that exceed max age
  board %>%
    pins::pin_search() %>%
    dplyr::filter(lubridate::now(tzone = "UTC") - created > lubridate::as.duration(!!max_age)) %$%
    name %>%
    pins::pin_delete(board = board)
}

#' Purge a package's user-cache pins board
#'
#' Deletes *all* objects from a package's user-cache pins board. All boards belonging to the same package as `board` are deleted, too.
#'
#' @inheritParams path_cache
#'
#' @family pkg_cache_mgmt
#' @export
purge_cache <- function(board) {
  
 path_cache(board) %>%
    fs::path_file() %>%
    stringr::str_extract("^[^-]+") %>%
    ls_board_paths() %>%
    purrr::walk(fs::dir_delete)
}

#' Purge all package user-cache pins boards
#'
#' Deletes the user-cache pins boards of *all* packages.
#'
#' @return The deleted filesystem [paths][fs::fs_path], invisibly. Of length 0 if no package user-cache pins boards did exist.
#' @family pkg_cache_mgmt
#' @export
purge_caches <- function() {
  
  fs::dir_delete(path = tools::R_user_dir(package = "pkgpins",
                                          which = "cache"))
}

#' Hash a function call
#'
#' Creates a string that uniquely identifies a function call by the function's name and a hash of the specified arguments.
#' 
#' `r foo <- function(a) pkgpins::hash_fn_call("foo", a); NULL`
#' 
#' This function does evaluate all arguments in `...`. I.e. the function call `mypkg::foo(a = my_var)` will be cached as `r pal::wrap_chr(foo(100))` if
#' `my_var`'s value is `100`, whereas it will become `r pal::wrap_chr(foo(101))` if `my_var`'s value is `101`. See examples below.
#'
#' @param from_fn Name of the function from which `hash_fn_call()` is called. A character scalar.
#' @param ... Arguments `from_fn` was called with. Any arguments omitted here won't be taken into account when generating the hash.
#'
#' @return A character scalar.
#' @family obj_handling
#' @export
#'
#' @examples
#' foo <- function(a, b = "default") pkgpins::hash_fn_call("foo", a, b)
#' 
#' foo("bar")
#' a <- "bar"
#' foo(a)
#' a <- "barbie"
#' foo(a)
#' a |> foo()
#' a |> foo(b = "default")
#' 
#' # you can also create a hash that is based on a subset of all function arguments
#' foo <- function(a, b = "default") pkgpins::hash_fn_call("foo", b)
#' 
#' foo("bar")
#' foo("barrr")
#' foo(b = "bar")
hash_fn_call <- function(from_fn,
                         ...) {
  
  checkmate::assert_string(from_fn)
  rlang::check_dots_unnamed()
  
  rlang::dots_list(...,
                   .homonyms = "error",
                   .ignore_empty = "trailing",
                   .preserve_empty = FALSE,
                   .check_assign = TRUE) %>%
    rlang::hash() %>%
    paste(from_fn, .,
          sep = "-")
}

#' Test whether an object exists in a package's user-cache pins board
#'
#' Returns `TRUE` if the object is present in the `pkg`'s user-cache pins board and hasn't exceeded `max_age`, otherwise `FALSE`.
#'
#' @inheritParams path_cache
#' @param id Pin name uniquely identifying the object to be checked in the `pkg`'s user-cache pins board. A character scalar.
#' @param max_age Maximum age the cached object is allowed to have. A valid [lubridate duration][lubridate::as.duration]. Defaults to 1 day (24 hours).
#'
#' @return A character scalar, or `NULL` if no cached object exists that hasn't exceeded `max_age`.
#' @family obj_handling
#' @export
is_cached <- function(board,
                      id,
                      max_age = "1 day") {
  
  checkmate::assert_string(id)
  checkmate::assert_class(board,
                          classes = "pins_board_folder")
  
  cache <- pins::pin_search(board = board)
  if (nrow(cache)) {
    
    cache %<>% dplyr::filter(name == id & lubridate::now(tzone = "UTC") - created <= lubridate::as.duration(!!max_age))
    
    if (nrow(cache) > 1L) {
      cli::cli_abort(paste0("Multiple pins with {.arg id} {.val {id}} found for the {.val {fs::path_file(board$path)}} board. This should not happen since ",
                            "versioning is disabled for pkgpins boards... \U1F41E"))
    }
  }
  
  nrow(cache) > 0L
}

#' Cache an object to a package's user-cache pins board
#'
#' Stores an object in `pkg`'s user-cache pins board, i.e. caches it to the filesystem.
#'
#' Note that `cache_obj()` will always overwrite an already existing cached object of the same `id`. See [hash_fn_call()] for a convenient way to create an `id`
#' that uniquely identifies a function call. Or just use [with_cache()] that internally relies on the former.
#'
#' Note that reading in the cached result from the user-cache pins board (i.e. from the filesystem) might produce a noticeable delay depending on the size of
#' the cached object. Therefore, it's only recommended to cache results that take a considerable amount of time to recompute. To avoid the overhead of
#' re-reading a cached result when accessing it multiple times, you can always assign it to an R variable to benefit from direct storage in memory.
#'
#' @inheritParams path_cache
#' @param x Object to be cached.
#' @param id Pin name uniquely identifying `x` in the `pkg`'s user-cache pins board. A character scalar which is safe to use in paths of common file systems.
#'   Necessary to retrieve `x` again using [get_obj()]. An already existing pin named `id` will be silently overwritten.
#' @param qs_preset The serialization algorithm preset to use. See [qs::qsave()] (section *Presets*) for details.
#'
#' @return `x`, invisibly.
#' @family obj_handling
#' @export
#'
#' @examples
#' # if the fn below would be part of a real package, we could instead define `this_pkg` globally
#' # using `this_pkg <- utils::packageName()`; instead, we now cache to pkgpins's cache (which
#' # itself never uses the cache)
#' board <- pkgpins::board(pkg = "pkgpins")
#' 
#' # let's define a fn that returns R pkg sys deps from cache
#' pkg_sys_deps <- function(pkg,
#'                          use_cache = TRUE,
#'                          cache_lifespan = "6h") {
#'   fetch <- TRUE
#'
#'   if (use_cache) {
#'     pin_name <- pkgpins::hash_fn_call(from_fn = "pkg_sys_deps",
#'                                       pkg)
#'     result <- pkgpins::get_obj(board = board,
#'                                id = pin_name,
#'                                max_age = cache_lifespan)
#'     fetch <- is.null(result)
#'   }
#'   
#'   if (fetch) {
#'     result <-
#'       jsonlite::fromJSON(txt = paste0("https://sysreqs.r-hub.io/pkg/", pkg),
#'                          simplifyVector = FALSE) |>
#'       purrr::list_flatten()
#'   }
#'  
#'   if (use_cache && fetch) {
#'     pkgpins::cache_obj(board = board,
#'                        x = result,
#'                        id = pin_name)
#'   }
#'
#'   result
#' }
#'
#' # now get the sys deps for git2r for the first time (populating the cache)
#' pkg_sys_deps("git2r")
#'
#' \dontrun{
#' # for the `cache_lifespan` (we've set a default of 6h), the cached result will be returned
#' # (as long as `use_cache = TRUE`):
#' bench::mark("with cache" = pkg_sys_deps("git2r"),
#'             "without cache" = pkg_sys_deps("git2r", use_cache = FALSE),
#'             iterations = 10,
#'             relative = TRUE)}
#' 
#' # purge cache from the above example
#' pkgpins::purge_cache(board = board)
cache_obj <- function(board,
                      x,
                      id,
                      qs_preset = c("fast", "balanced", "high", "archive")) {
  
  checkmate::assert_class(board,
                          classes = "pins_board_folder")
  checkmate::assert_string(id,
                           pattern = "^[^/\\\\]+$")
  qs_preset <- rlang::arg_match(qs_preset)
  
  # ensure `id` is safe to use as fs path
  if (id != fs::path_sanitize(id)) {
    cli::cli_abort("{.arg id} contains characters which are not safe to use in common file system paths, cf. {.code ?fs::path_sanitize}")
  }
  
  # serialize obj
  date_time_created <- format(Sys.time(),
                              "%Y%m%dT%H%M%SZ",
                              tz = "UTC")
  path_dir <-
    path_cache(board) %>%
    fs::path(id, glue::glue("{date_time_created}-00000")) %>%
    fs::dir_create()
  
  path_file <- "cache.qs"
  path <- fs::path(path_dir, path_file)
  
  qs::qsave(x = x,
            file = path,
            preset = qs_preset,
            check_hash = TRUE)
  
  # write pin metadata
  yaml::write_yaml(x = list(file = path_file,
                            file_size = as.integer(fs::file_size(path)),
                            # pin hash is omitted since a) not sensible for our purpose and b) `qs::qsave()` stores an integrity hash in file anyways
                            pin_hash = NULL,
                            type = "qs",
                            title = id,
                            description = NULL,
                            created = date_time_created,
                            api_version = 1,
                            user = NULL),
                   file = fs::path(path_dir, "data.txt"))
}

#' Get a cached object from a package's user-cache pins board
#'
#' Retrieves a cached object from a package's user-cache pins board _if_ it is not older than `max_age`.
#'
#' @inheritParams is_cached
#' @param id Pin name uniquely identifying the object to be retrieved from the `pkg`'s user-cache pins board. A character scalar.
#'
#' @return The cached object if it is not older than `max_age`, otherwise `NULL`.
#' @family obj_handling
#' @export
get_obj <- function(board,
                    id,
                    max_age = "1 day") {
  
  if (is_cached(board = board,
                id = id,
                max_age = max_age)) {
    
    result <- pins::pin_read(board = board,
                             name = id)
  } else {
    result <- NULL
  }
  
  result
}

#' Delete a cached object from a package's user-cache pins board
#'
#' Removes a cached object from a package's user-cache pins board.
#'
#' Note that it normally won't be necessary to delete a cached object using this function because [cache_obj()] will always overwrite a possibly existing object
#' in the cache with the same `id`. If you want to ensure that no "data corpses" are left behind from using [cache_obj()], consider [clearing][clear_cache] or
#' even [purging][purge_cache] the whole package user-cache pins board at once.
#'
#' @inheritParams path_cache
#' @param id Pin name uniquely identifying the object to be deleted from the `pkg`'s user-cache pins board. A character scalar.
#'
#' @return `id`, invisibly.
#' @family obj_handling
#' @export
rm_obj <- function(board,
                   id) {
  
  checkmate::assert_class(board,
                          classes = "pins_board_folder")
  checkmate::assert_string(id)
  
  pins::pin_delete(board = board,
                   names = id)
  invisible(id)
}
